### ISSUE TITLE
關閉屏不會計算

### ISSUE THREAD

**Issue by hksfho** [xfmax/BasePedo#1]
關閉屏後不會好像計算步數

**Comment by xfmax** [comment]
Please let me know mobile phone models and system version

**Comment by hksfho** [comment]
s5 G906S 韓版
android5.0.2

**Comment by hksfho** [comment]
如果閉屏後,service會自動關閉

**Comment by hksfho** [comment]
我把priority設成2147483647
service沒有被關閉,但閉屏後也不會計步

**Comment by xfmax** [comment]
也就是说，开着屏幕是可以计步？我手上暂时没有S5，要周一去单位看看才能回复你，你可以自己先尝试修改代码。麻烦使用 adb shell dumpsys sensorservice,截个图发上来，我也可以看看有没有用运动传感器。

**Comment by xfmax** [comment]
麻烦使用 adb shell dumpsys sensorservice,截个图发上来，我看看有没有用运动传感器。

**Comment by hksfho** [comment]
鎖屏>不能計步
解鎖之後就能計步

**Comment by hksfho** [comment]
我在google play上找了幾個計步器,都能在閉屏後計步,
估計不是設備的問題.

**Comment by xfmax** [comment]
我不是让你验证设备问题，我要看支持的传感器都有哪几种，我手里没有S5，没法看

**Comment by xfmax** [comment]
公司没有S5，但是有S6，我估计应该在传感器方面都一样，经验证，S6前台和后台都能稳定计步，你再试试我最新打的包吧

**Comment by hksfho** [comment]
不行,我拍了一條短片,我放上youtube,你那邊能上youtube嗎?

**Comment by xfmax** [comment]
我们别再Issue聊了，发邮件吧

**Comment by hksfho** [comment]
qq 有嗎

**Comment by xfmax** [comment]
QQ:396191344
2016年3月21日 20:26，"hksfho" <notifications@github.com>写道：
