### ISSUE TITLE
请教问题

### ISSUE THREAD

**Issue by mingmingacc** [xfmax/BasePedo#10]
按返回键退出，步数会回到最开始的地方，请问又解决办法吗

**Comment by xiaocainiaooo** [comment]
请教一下  关于service保活 这个测试过么

**Comment by xfmax** [comment]
请问使用的是什么手机？可以稳定复现这种bug吗？

**Comment by xiaocainiaooo** [comment]
华为手机  我熄灭屏后 几秒钟后  adb shell   
ps  发现进程已经没有了

**Comment by xfmax** [comment]
进程保活没有万能之法，没办法。
