### ISSUE TITLE
魅蓝Note2安装上为什么直接就有682步？

### ISSUE THREAD

**Issue by linglongxin24** [xfmax/BasePedo#2]

**Comment by xfmax** [comment]
google在android4.4版本之后，提供了一个内置计步器，该计步器读取的是从开机到现在被记录的数据，也就是说你没安装之前就已经走了682步，具体细节，请仔细阅读android开发者平台的相关文档。

**Comment by linglongxin24** [comment]
那如何让你这个计步代码装上的时候从零开始算呢？

**Comment by xfmax** [comment]
第一次获取到的值不直接用于显示，而是作为一个初始值，比如682，下次回调方法再返回700的时候，用700减去682，得到的值就是正确的值。

**Comment by linglongxin24** [comment]
你好，数据为什么在晚上12点之后不变成0还是前一天的数据？

**Comment by wei6718189** [comment]
作者已经说了...从开机到现在被记录的数据
