### ISSUE TITLE
第二天 或者更改日期后，如何让记步数初始化。

### ISSUE THREAD

**Issue by wei6718189** [xfmax/BasePedo#4]

**Comment by xfmax** [comment]
如果使用google提供的内置计步器，需要记住每次由传感器传回的值，在进行置零操作。

**Comment by wei6718189** [comment]
goolgle提供的内置计步器 还没研究过。那你这个demo 呢 我直接StepDcretor.CURRENT_SETP初始化，记步器继续记录上一天的，把应用关了之后，重新打开才行？

**Comment by xfmax** [comment]
我这里就是使用了google的内置计步器，如果你的手机支持，会优先使用的，我假定你用的这个计步器，那么传感器回调的方法里有最新的传感器数据，但是它记录的是从开机到现在的，剩下的，你自己看着办就可以了

**Comment by wei6718189** [comment]
哦 了解 谢谢~

**Comment by iboying** [comment]
我暂时的做法是：因为大概30-60秒就会执行一次save()操作，这时获取一下当前时间，当数据库没有这条记录时，说明应该是新的一天，然后执行：UpdateNotification(); StepDcretor.CURRENT_SETP=0; 我用4.3的测试机测试的暂时工作正常，大家多交流，分享一下经验

**Comment by wei6718189** [comment]
嗯 后面我也发现了 也是这么做的  :)

**Comment by xfmax** [comment]
最新版本已添加跨天清零操作。
