### ISSUE TITLE
数据库保存在哪个位置的问题，谷歌算法不显示到界面问题

### ISSUE THREAD

**Issue by wang2016215** [xfmax/BasePedo#8]
我在手机上没有找到数据库的那个文件 不知道保存在哪了 求解答，还有就是我用addCountStepListener();这个方法 主界面的步数没有改变。。。求大神解答解答

**Comment by iboying** [comment]
没有详细描述啊，看不出想要问什么

**Comment by iboying** [comment]
源码不多，你可以看一下源码就知道了，`addCountStepListener();`只是设置步数监听，改变`StepCreator.CURRENT_STEP`，然后通过消息通知主界面当期步数， 你看一下`StepService.java`的MessengerHandler`相关的代码就知道了，（数据库文件，百度吧，一堆）

**Comment by wang2016215** [comment]
大神，还有一个问题，努比亚手机 三星手机 和联想的手机步数相差比较大 机型适配应该怎么做呢

**Comment by iboying** [comment]
机型适配就有点问题了，我做我们的项目的时候，基本都能计步，适配主要是华为的手机问题比较多。
   `BasePedo`计步器使用的是加速度传感器，所以只是使用`BasePedo`的话，步数应该都差不多，反而是使用系统自带计步器差别比较大，所以后来我都改成使用`BasePedo`了，，你也可以，根据手机系统版本判断，高版本使用系统计步器，低版本使用BasePedo或者不提供计步（微信运动就不支持4.4以下的Android机）。（另外，我是小菜不是大神，还有，Android 计步器不比过于纠结精度，谁让Android系统没有iOS的`健康`这样的应用呢）。

**Comment by xfmax** [comment]
确实，苹果的健康确实牛逼啊，接口给的非常完善，再看看android那提供的功能，实在太简单了，只返回一个步数，个人认为这确实是google还没进行完善的一个测试性功能。
