### ISSUE TITLE
4.4计步的问题

### ISSUE THREAD

**Issue by bacy** [xfmax/BasePedo#9]
4.4之后，步数取的是系统的count，但是这个count是app注册以来的总步数，并不是每天的步数，所以会导致步数一天比一天大

**Comment by iboying** [comment]
两种方案：
1、你不用取系统计步器的值，只调用系统计步器的`onSensorChanged`，然后变化一次，就说明增加一步。
2、取系统计步器的值，但是要自己保存这个值，以后取到的步数减去这个初始步数，也能实现计步

**Comment by xfmax** [comment]
@iboying 说的很对，请参考采纳，如果有更好的方式，也请说出来，一起来完善。
